title: rshyper
description: rshyper is a performant framework for hypergraphs in Rust.
tagline: A hypergraph framework for Rust

author: FL03
email: support@scsys.io
domain: fl03.github.io
keywords: [hypergraph, rust, graph theory, data analysis]
remote_theme: just-the-docs@v0.10.1
theme: just-the-docs
url: https://fl03.github.io/rshyper

collections:
  guides:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /:collection/:path/
    sort_by: date

just_the_docs:
  collections:
    guides:
      name: Guides
    posts:
      name: Blog

aux_links:
  GitHub:
    - https://github.com/fl03/rshyper
  crates.io:
    - https://crates.io/crates/rshyper
  docs.rs:
    - https://docs.rs/rshyper

