title: rshyper
description: rshyper is a performant framework for hypergraphs in Rust.
tagline: A hypergraph framework for Rust

author: FL03
email: support@scsys.io
domain: fl03.github.io
keywords: [hypergraph, rust, graph theory, data analysis]
remote_theme: just-the-docs@v0.10.1
theme: just-the-docs
url: https://fl03.github.io/rshyper

collections:
  docs:
    output: true
    permalink: /docs/:path/
    sort_by: date
  posts:
    output: true
    permalink: /blog/:path/
    sort_by: date

just_the_docs:
  collections:
    docs:
      name: Documentation
    posts:
      name: Blog

# External navigation links
nav_external_links:
  - title: Repository
    url: https://github.com/fl03/rshyper
    opens_in_new_tab: true
  - title: crates.io
    url: https://crates.io/crates/rshyper
    opens_in_new_tab: true
  - title: docs.rs
    url: https://docs.rs/rshyper
    opens_in_new_tab: true
