source 'https://rubygems.org'

gem "jekyll", "~> 4.2"

gem "just-the-docs"        # always download the latest release

group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-remote-theme"
  gem "jekyll-timeago", "~> 0.13.1"
end
